/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libgts_JNI */

#ifndef _Included_com_libgts_JNI
#define _Included_com_libgts_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_libgts_JNI
 * Method:    analysisAudioClip
 * Signature: ([BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libgts_JNI_analysisAudioClip
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
